### ISSUE TITLE
Issues when running wLE_ISR from MC1

### ISSUE THREAD

**Issue by Windows10User2** [israpps/wLaunchELF_ISR#62] opened 2024-01-27 16:32 UTC
### Checks

- [ ] I have checked existing [__Issue reports__](https://github.com/israpps/wLaunchELF_ISR/issues) for duplicates and found none
- [ ] I downloaded wLaunchELF from this repository or the [official download link](https://israpps.github.io/20210113_wLaunchELF_isr/)

### Console model

SCPH-75004

### wLaunchELF commit code

945d787 

### Describe the issue

If running wLE_ISR's BOOT-EXFAT-DS34-MX4SIO version from MC1, changing its IP address in "Network Settings..." and clicking "Save to "mc1:/BOOT/IPCONFIG.DAT", it says "Saved Failed". Also, if running wLE_ISR's BOOT-EXFAT-DS34-MX4SIO version from MC1, assigning a button and clicking "OK", it says "Failed To Save LAUNCHELF.CNF". wLE_ISR's BOOT version doesn't have these issues.

**Comment by MayanKoyote** [comment] 2024-02-06 06:36
https://github.com/israpps/wLaunchELF_ISR/issues/36

**Comment by israpps** [comment] 2024-02-06 13:03
Duplicate of #36

**Closed by israpps** 2024-02-06 13:03 UTC
Labels: bug
