### ISSUE TITLE
Weird issues

### ISSUE THREAD

**Issue by Windows10User2** [israpps/wLaunchELF_ISR#81] opened 2024-07-26 16:54 UTC
### Checks

- [ ] I have checked existing [__Issue reports__](https://github.com/israpps/wLaunchELF_ISR/issues) for duplicates and found none
- [ ] I downloaded wLaunchELF from this repository or the [official download link](https://israpps.github.io/20210113_wLaunchELF_isr/)

### Console model

SCPH-75004

### wLaunchELF commit code

bc17c7d

### Describe the issue

When running wLE_ISR on the PS2 and clicking on a folder ("mc0:/", for instance), it often opens it and immediately turns back, not to mention sometimes nothing happens after clicking a button (inside and outside wLE_ISR) or I have drift (outside wLE_ISR). 

Maybe it's Brook Super Converter's and/or DualShock 3's fault or even a combination of it and wLE_ISR, since the 2 former may cause these issues outside wLE_ISR (and maybe the problem regarding nothing happening when clicking a button inside wLE_ISR) and the latter (wLE_ISR) might have a bug that causes the first described issue.

I have to restart the PS2 when I have these problems.

**Comment by israpps** [comment] 2024-07-26 23:15
Duplicate of #13

**Closed by israpps** 2024-07-26 23:15 UTC
Labels: bug

**Comment by Windows10User2** [comment] 2024-07-27 11:35
What about the issue regarding nothing happening after clicking a button on wLE_ISR?
